In [248]:
string=['my name is hakesh kumar',
         'i am working in moengage company',
        'my role in the company is solution engineer',
        'i am very much interested in machine learning']

In [311]:
import numpy as np

s=1+np.log((4)/(3))
print(s)

1.2876820724517808


In [250]:
string

['my name is hakesh kumar',
 'i am working in moengage company',
 'my role in the company is solution engineer',
 'i am very much interested in machine learning']

In [272]:
from tqdm import tqdm 
from sklearn.preprocessing import normalize
def fit(dataset):    
    unique_words = set()
    if isinstance(dataset, (list)):
        for row in dataset: 
            for word in row.split(" "): 
                if len(word) < 2:
                    continue
                unique_words.add(word)
        unique_words = sorted(list(unique_words))
        vocab = {j:i for i,j in enumerate(unique_words)}
        return vocab
    else:
        print("you need to pass list of sentance")

In [274]:
vocab=fit(string)
print(vocab)

{'am': 0, 'company': 1, 'engineer': 2, 'hakesh': 3, 'in': 4, 'interested': 5, 'is': 6, 'kumar': 7, 'learning': 8, 'machine': 9, 'moengage': 10, 'much': 11, 'my': 12, 'name': 13, 'role': 14, 'solution': 15, 'the': 16, 'very': 17, 'working': 18}


# Comparing FIT and SKLearn  alphabetical order 

In [254]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit(string)
#skl_output = vectorizer.transform()

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [276]:
print(vectorizer.get_feature_names())
print(list(vocab))

['am', 'company', 'engineer', 'hakesh', 'in', 'interested', 'is', 'kumar', 'learning', 'machine', 'moengage', 'much', 'my', 'name', 'role', 'solution', 'the', 'very', 'working']
['am', 'company', 'engineer', 'hakesh', 'in', 'interested', 'is', 'kumar', 'learning', 'machine', 'moengage', 'much', 'my', 'name', 'role', 'solution', 'the', 'very', 'working']


In [256]:
import numpy as np

In [301]:
A=list(string)
print(A)



['my name is hakesh kumar', 'i am working in moengage company', 'my role in the company is solution engineer', 'i am very much interested in machine learning']


In [307]:
test= 'my name is hakesh kumar i am working in moengage company my role in the company is solution engineer i am very much interested in machine learning'  


AttributeError: 'dict' object has no attribute 'count'

# Transform 

In [259]:
# https://stackoverflow.com/questions/9919604/efficiently-calculate-word-frequency-in-a-string
# https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.sparse.csr_matrix.html
# note that we are we need to send the preprocessing text here, we have not inlcuded the processing
from collections import Counter
from scipy.sparse import csr_matrix
def transform(dataset,vocab):
    rows = []
    columns = []
    values = []
    if isinstance(dataset, (list,)):
        for idx, row in enumerate(tqdm(dataset)): # for each document in the dataset
            # it will return a dict type object where key is the word and values is its frequency, {word:frequency}
            word_freq = dict(Counter(row.split()))
            # for every unique word in the document
            for word, freq in word_freq.items():  # for each unique word in the review.                
                if len(word) < 2:
                    continue
                # we will check if its there in the vocabulary that we build in fit() function
                # dict.get() function will return the values, if the key doesn't exits it will return -1
                col_index = vocab.get(word, -1) # retreving the dimension number of a word
                # if the word exists
                if col_index !=-1:
                    # we are storing the index of the document
                    rows.append(idx)
                    # we are storing the dimensions of the word
                    columns.append(col_index)
                    # we are storing the frequency of the word
                    values.append(freq)
        return csr_matrix((values, (rows,columns)), shape=(len(dataset),len(vocab)))
    else:
        print("you need to pass list of strings")

In [260]:
transform(string,vocab)

100%|██████████| 4/4 [00:00<00:00, 2162.29it/s]


<4x19 sparse matrix of type '<class 'numpy.int64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [261]:
print(list(vocab.keys()))
print(transform(string, vocab).toarray())

100%|██████████| 4/4 [00:00<00:00, 5355.00it/s]

['am', 'company', 'engineer', 'hakesh', 'in', 'interested', 'is', 'kumar', 'learning', 'machine', 'moengage', 'much', 'my', 'name', 'role', 'solution', 'the', 'very', 'working']
[[0 0 0 1 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0]
 [1 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1]
 [0 1 1 0 1 0 1 0 0 0 0 0 1 0 1 1 1 0 0]
 [1 0 0 0 1 1 0 0 1 1 0 1 0 0 0 0 0 1 0]]


In [262]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn import preprocessing
vec = CountVectorizer(analyzer='word')

vec.fit(string)
feature_matrix_2 = vec.transform(string)
print(feature_matrix_2.toarray())

[[0 0 0 1 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0]
 [1 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1]
 [0 1 1 0 1 0 1 0 0 0 0 0 1 0 1 1 1 0 0]
 [1 0 0 0 1 1 0 0 1 1 0 1 0 0 0 0 0 1 0]]


In [263]:
a=transform(string, vocab)

100%|██████████| 4/4 [00:00<00:00, 3445.01it/s]


In [264]:
b=normalize(a, norm='l2', )

In [265]:
print(b[0].toarray())

[[0.        0.        0.        0.4472136 0.        0.        0.4472136
  0.4472136 0.        0.        0.        0.        0.4472136 0.4472136
  0.        0.        0.        0.        0.       ]]


In [266]:
tf_idf_vect=TfidfVectorizer()

In [267]:
tf_idf_vect.fit(string)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [268]:
out=tf_idf_vect.transform(string)

In [269]:
tf_idf_vect.idf_

array([1.51082562, 1.51082562, 1.91629073, 1.91629073, 1.22314355,
       1.91629073, 1.51082562, 1.91629073, 1.91629073, 1.91629073,
       1.91629073, 1.91629073, 1.51082562, 1.91629073, 1.91629073,
       1.91629073, 1.91629073, 1.91629073, 1.91629073])

In [270]:
out.shape

(4, 19)

In [271]:
print(out[0].toarray())

[[0.         0.         0.         0.48546061 0.         0.
  0.38274272 0.48546061 0.         0.         0.         0.
  0.38274272 0.48546061 0.         0.         0.         0.
  0.        ]]
